/*
 * This file is part of the Visualization of Protein Ligand Graphs (VPLG) software package.
 *
 * Copyright Tim Schäfer 2012. VPLG is free software, see the LICENSE and README files for details.
 *
 * @author ts
 */

package vpg;

/**
 * The about frame which shows basic info on this software and its version.
 * @author ts
 */
public class VpgAboutFrame extends javax.swing.JFrame {

    /**
     * Creates new form VpgAboutFrame
     */
    public VpgAboutFrame() {
        initComponents();
        this.jTitleLabel.setText("Vpg -- A frontend for VPLG     (VPG version: " + Settings.getVersion() + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jContentPanel = new javax.swing.JPanel();
        jTitleLabel = new javax.swing.JLabel();
        jScrollPaneInfoText = new javax.swing.JScrollPane();
        jTextAreaInfoText = new javax.swing.JTextArea();

        jTitleLabel.setText("Vpg -- A frontend for VPLG");
        jTitleLabel.setMaximumSize(new java.awt.Dimension(1200, 1000));
        jTitleLabel.setMinimumSize(new java.awt.Dimension(100, 75));

        jTextAreaInfoText.setBackground(new java.awt.Color(230, 230, 230));
        jTextAreaInfoText.setColumns(20);
        jTextAreaInfoText.setEditable(false);
        jTextAreaInfoText.setRows(5);
        jTextAreaInfoText.setText("This software is part of the Visualization of Protein Ligand Graphs (VPLG) package.\nVPLG is free software and comes without any warranty. See the LICENSE and README\nfiles for details.\n\nVPLG was written by Tim Schäfer at the Molecular Bioinformatics group of Ina Koch at\nGoethe University Frankfurt am Main. See http://www.bioinformatik.uni-frankfurt.de \nfor contact data.\n\nThe VPLG website is at http://vplg.sourceforge.net.");
        jTextAreaInfoText.setToolTipText("About contents");
        jScrollPaneInfoText.setViewportView(jTextAreaInfoText);

        javax.swing.GroupLayout jContentPanelLayout = new javax.swing.GroupLayout(jContentPanel);
        jContentPanel.setLayout(jContentPanelLayout);
        jContentPanelLayout.setHorizontalGroup(
            jContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneInfoText, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addComponent(jTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jContentPanelLayout.setVerticalGroup(
            jContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneInfoText, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VpgAboutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VpgAboutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VpgAboutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VpgAboutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VpgAboutFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jContentPanel;
    private javax.swing.JScrollPane jScrollPaneInfoText;
    private javax.swing.JTextArea jTextAreaInfoText;
    private javax.swing.JLabel jTitleLabel;
    // End of variables declaration//GEN-END:variables
}
