<?php
/* This file is auto-generated by the maintenance page of the PTGL, do not edit it manually. Run an admin maintenance task on the page instead. */
$last_update_month_and_year = "February 2015";
$num_pdb_files = 28;
$num_protein_chains = 104;
$num_protein_chains_nonredundant = 0;
$num_sses = 2340;
$num_intrachain_contacts = 2264;
$num_helices = 1186;
$num_strands = 996;
$num_ligands = 158;
$num_sses_in_alphagraphs = 1186;
$num_sses_in_betagraphs = 996;
$num_sses_in_albegraphs = 2182;
$num_sses_in_alphaliggraphs = 1344;
$num_sses_in_betaliggraphs = 1154;
$num_sses_in_albeliggraphs = 2340;
$num_contacts_mixed = 617;
$num_contacts_parallel = 354;
$num_contacts_antiparallel = 696;
$num_contacts_ligand = 597;
$num_graphs_alpha = 102;
$num_graphs_beta = 102;
$num_graphs_albe = 102;
$num_graphs_alphalig = 102;
$num_graphs_betalig = 102;
$num_graphs_albelig = 102;
$num_graphs_alpha_with_barrel = 0;
$num_graphs_beta_with_barrel = 12;
$num_graphs_albe_with_barrel = 12;
$num_graphs_alphalig_with_barrel = 0;
$num_graphs_betalig_with_barrel = 12;
$num_graphs_albelig_with_barrel = 12;
?>
