<?php
/* This file is auto-generated by the maintenance page of the PTGL, do not edit it manually. Run an admin maintenance task on the page instead. */
$last_update_month_and_year = "January 2015";
$num_pdb_files = 1;
$num_protein_chains = 1;
$num_sses = 31;
$num_intrachain_contacts = 32;
$num_helices = 16;
$num_strands = 13;
$num_ligands = 2;
$num_sses_in_alphagraphs = 16;
$num_sses_in_betagraphs = 13;
$num_sses_in_albegraphs = 29;
$num_sses_in_alphaliggraphs = 18;
$num_sses_in_betaliggraphs = 15;
$num_sses_in_albeliggraphs = 31;
$num_contacts_mixed = 5;
$num_contacts_parallel = 9;
$num_contacts_antiparallel = 8;
$num_contacts_ligand = 10;
$num_graphs_alpha = 1;
$num_graphs_beta = 1;
$num_graphs_albe = 1;
$num_graphs_alphalig = 1;
$num_graphs_betalig = 1;
$num_graphs_albelig = 1;
$num_graphs_alpha_with_barrel = 0;
$num_graphs_beta_with_barrel = 0;
$num_graphs_albe_with_barrel = 0;
$num_graphs_alphalig_with_barrel = 0;
$num_graphs_betalig_with_barrel = 0;
$num_graphs_albelig_with_barrel = 0;
?>
