<?php
/* This file is auto-generated by the maintenance page of the PTGL, do not edit it manually. Run an admin maintenance task on the page instead. */
$last_update_month_and_year = "June 2020";
$num_pdb_files = 151837;
$num_large_structures = 921;
$num_protein_chains = 505337;
$num_protein_chains_nonredundant = 0;
$num_sses = 9003153;
$num_intrachain_contacts = 10504673;
$num_helices = 4193575;
$num_strands = 3833407;
$num_ligands = 976171;
$num_sses_in_alphagraphs = 4193575;
$num_sses_in_betagraphs = 3833407;
$num_sses_in_albegraphs = 8026982;
$num_sses_in_alphaliggraphs = 5169746;
$num_sses_in_betaliggraphs = 4809578;
$num_sses_in_albeliggraphs = 9003153;
$num_contacts_mixed = 5081486;
$num_contacts_parallel = 1390169;
$num_contacts_antiparallel = 3139206;
$num_contacts_ligand = 893812;
$num_graphs_alpha = 478477;
$num_graphs_beta = 478477;
$num_graphs_albe = 478477;
$num_graphs_alphalig = 478477;
$num_graphs_betalig = 478477;
$num_graphs_albelig = 478477;
$num_graphs_alpha_with_barrel = 0;
$num_graphs_beta_with_barrel = 14904;
$num_graphs_albe_with_barrel = 14903;
$num_graphs_alphalig_with_barrel = 0;
$num_graphs_betalig_with_barrel = 14904;
$num_graphs_albelig_with_barrel = 14903;
?>
