#!/bin/bash

## check for java in PATH
which java > /dev/null
if [ $? -ne 0 ]; then
    echo "ERROR: Could not find 'java' executable in PATH. Is the JRE installed?"
    exit 1
fi

## k, run
java -Xms 5G -Xms 5G -jar plcc.jar $@
